language: node_js
matrix:
  fast_finish: true
node_js:
- '6'
branches:
  except:
  - build
env:
  global:
  - CXX=g++-4.8
  - secure: bgiiNIIzsIFPRCl5LwFUk4X6sShbf7do4TntQNO3LwnpOw8fhXYSly9+A6Cq0E9SPU6s0T9W2qYsZ3C0/01A0dp4rYnvGI3aN2zMEto36aoJjC69vilV2XB18r2fo5qYz6NJw2O0VOp7lLvtL9fCaeB0gV6G5rtZv5iTheHkUxtG0td7AavbbgcM++dun+9yB5TgxoskJ3HLjBT2c0MdCE4rguc/vP2DJkHPQBlbogqzT+iua3I5TAsK7s6rKMUD0Lv00YYXD6qctm1R61RE/wab7XP9t1hEEYzRosck0WYa2RdNwtRn/CM+qxbO3Zzgr7yfeJla2XD6xGQEDKhp7hd5/YRx7jBBDkTENl3zXV2VZCgo9LnJHrtf1JqAn/EB3SrX0A+jZRJyFSc+gsal1dyCawZ2X1F6P5YGTqbYOrlctUmlhIQUYxD4zY12aS7Y6h145bzvQW9En+M+etXQtMZCb3BMVllls+Ff4Cvt9zOxdRTMA9FOdrBCemummRcDF+BQBD2xSCvUKwSrd3VTkJP/FBRPE5cby+I03//1JS3plcjYKyKbMhmeHY7/E3IZg6b3lM4GvXJt0UXmiVyONMIotUNM+jQERGH0HcgTme409AqrxHZPHh6n1XIgxaeTkn/PyKaHlbhEQlZILlZMwMaycux/LEDFDVxsICQRZTM=
  - secure: ngMP1cQJga57o082DBMyTXLN8LP7/kGEPQoETltvahlidzChXkQO08kGA1iFquldg/3DnZujCc3MioLgHgFeRBIC6c/OYXD68Jylmd44h6/rKcN7ovfQjAKYJ49yuyqEC9T30va+emWEwuC6nTs4+/cEPSdz+RMYIZg4/KhFutszfUzwYgPSgv/0L/veSiL5Byn858dvRPFPgH1UiaNmTFPptT7YRL0YA1owSEZPgOfsZ4Zm/FBa+qktGIFwQgIhZlO+5sXIIP/QeEVjQCc+PeLByUCyA6x3zvUTHFchZEeBXCBfHRFFGuSuWRYvRPtfPZCbGIjcfjw1Ce4KAJFsnihymXLFPkdf4/gQW/Rk9IQQiHEKZgEq2OJuTn/eDzD+wG7QTUiGT03Y+kt6oMYEj3IrKr/c56r9+cOkAbftx+3HjEfgEPvVrpwtGAXkc8jYKhv7klUuHUd4QSNFnh2uVtGUwOzOlzbHkgxVITvb0M+glGcz7IEcZsZ+Lc73VJlFLS4oi/Z9f167niBWRQRD2qzPseU+bP2TJSCFMi5kW4AlvG3k6Yw9Y/WX1kGNAN9lGrH4KOrwsTLaMd0+4kPG25RSSiqMenpWuC1HMabnSEGj4q6NmrZo5N5mGCY/+QgHMdhOX3EqvQ6WuGWii5VNJtESvi3MdMxKkT+/cqhm2+o=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    packages:
    - g++-4.8
    - python3.5
cache:
  directories:
  - node_modules
before_script:
- curl -fsSL https://bootstrap.pypa.io/get-pip.py | python3.5 - --user
- travis_retry pip3.5 install --user transifex-client
- install -m0644 .transifexrc.tpl ~/.transifexrc
- echo "password = $TX_PASSWD" >> ~/.transifexrc
script:
- npm run build
- npm run test
after_success:
- test $TRAVIS_BRANCH = "master" && npm run deploy
